services:

  chat_service_mongo:
    image: mongo:6
    container_name: chat_service_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - chat_service_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  chat_service_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: chat_service_app
    ports:
      - "127.0.0.1:8081:8080"
    env_file:
      - .env

  chat_service_cmd:
    build:
      context: .
      dockerfile: docker/cmd/Dockerfile
    container_name: chat_service_cmd
    env_file:
      - .env

volumes:
  chat_service_mongo_data:
