services:
  chat_service_mongo_test:
    image: mongo:6
    container_name: chat_service_mongo_test
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  chat_service_app_test:
    container_name: chat_service_app_test
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./mount:/mount
    working_dir: /app
    env_file:
      - .env.test

  chat_service_redis_test:
    image: redis:7
    container_name: chat_service_redis_test
    restart: unless-stopped
